### ISSUE TITLE
REEDS-to-USLCI grid mix changes- We should have that code in the repo, along with the raw data from REEDS.

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#113]

**Comment by TJTapajyoti** [comment]
The REEDS dataset needs to be modified manually before the final arrangement into the celavi readable file. 
The manual workflow requires renaming of electricity flows and combining different electricity generation sources into sources matching the USLCI electricity flows.
@rjhanes 
Does this manual process needs to be automated?

**Comment by rjhanes** [comment]
I think it's OK to leave the modifications as manual, provided the changes to be made are documented somewhere.

**Comment by TJTapajyoti** [comment]
@rjhanes I have created a manual for this task. A part of the operation is also done using a python script. Can you please guide me where to place the code as well the manual document @rjhanes
