### ISSUE TITLE
Revise docstrings in Router, ComputeLocations and DataManager

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#127]
- [x] `node_locations` parameter description in `ComputeLocations.__init__`
- [x] `node_locations` parameter description in `Router.get_all_routes`
- [x] `TransportationNodeLocations(Data)` docstring
- [x] #132

**Comment by eberlea** [comment]
@rjhanes I think I addressed all of these issues in the latest commit to develop (referenced above; 
Closes issue #127). Let me know if anything is unclear or unanswered. Once you've reviewed, please close this issue.
