### ISSUE TITLE
Facilities missing error component.py - (National data repo branch + develop code branch) - Filtering on IA MO

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#129]
Facility 56789 does not exist in CostGraph
Facility 56790 does not exist in CostGraph
Facility 56792 does not exist in CostGraph
Facility 56794 does not exist in CostGraph
Facility 56795 does not exist in CostGraph
Facility 56805 does not exist in CostGraph
Facility 56818 does not exist in CostGraph
Facility 56819 does not exist in CostGraph
Facility 56829 does not exist in CostGraph
Facility 56835 does not exist in CostGraph
Facility 56836 does not exist in CostGraph
Facility 56837 does not exist in CostGraph
Facility 56838 does not exist in CostGraph
Facility 56841 does not exist in CostGraph
Facility 56842 does not exist in CostGraph
Facility 56854 does not exist in CostGraph
Facility 56856 does not exist in CostGraph
Facility 56874 does not exist in CostGraph
.......
.......
Facility 10000153 does not exist in CostGraph
Facility 10000153 does not exist in CostGraph
Facility 10000154 does not exist in CostGraph
Facility 10000155 does not exist in CostGraph

Updating cost graph
2022-01-18 10:23:13.977048 In While loop update cost graph
2022-01-18 10:23:13.977077 In While loop pylca interface
Traceback (most recent call last):
  File "/Users/tghosh/OneDrive - NREL/work_NREL/CELAVI/celavi/celavi/celavi/component.py", line 131, in bol_process
    count_inventory = self.context.count_facility_inventories[self.current_location]
KeyError: 'manufacturing_nan'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__main__.py", line 550, in <module>
    count_facility_inventories = context.run()
  File "/Users/tghosh/OneDrive - NREL/work_NREL/CELAVI/celavi/celavi/celavi/des.py", line 441, in run
    self.env.run(until=int(self.max_timesteps))
  File "/Users/tghosh/miniconda3/envs/celavi/lib/python3.8/site-packages/simpy/core.py", line 254, in run
    self.step()
  File "/Users/tghosh/miniconda3/envs/celavi/lib/python3.8/site-packages/simpy/core.py", line 206, in step
    raise exc
KeyError: 'manufacturing_nan
[netw.csv](https://github.com/NREL/celavi/files/7891148/netw.csv)
[netw.csv](https://github.com/NREL/celavi/files/7891151/netw.csv)
'

**Comment by rjhanes** [comment]
The problem was that the technology units file was being read in and saved as a data frame before any filtering was done. So any runs where the location-based filtering didn't match the filtering in the previous run, Context would be running off a different facility dataset than CostGraph. That's why the bug was intermittent - the first run of a scenario would break, and then the second one would be fine because the filtering was already done. I moved the file read-in for the technology units to just before the component creation (after filtering) which should eliminate this bug.
