### ISSUE TITLE
array uncertainty leads to "LCA inventory does not exist for cement co-processing"

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#160]
@TJTapajyoti I could use some help with this issue. I'm testing the `array-uncertainty` branch, commit [f841e97](https://github.com/NREL/celavi/pull/159/commits/f841e97cad6e0fbd55ae8923eaeffa46a9dc49c2), on the `tiny-array-uncertainty` data branch, commit [eaef1ce](https://github.nrel.gov/akey/celavi-data/commit/eaef1ce0b48a7e6ec56d3f39dd0e4b4e51c167cb), using both YAML files in the data repo. You can see the changes in `array-uncertainty` relative to `develop` in PR #159 - I updated the cost methods primarily and made minor changes to three other files. I'm now seeing a missing LCA inventory starting in 2032:

```
LCA inventory does not exist for 2032 cement co-processing glass fiber
LCA inventory does not exist for 2032 cement co-processing epoxy
```

All other LCIA calculations, shortcut and from scratch, appear to be executing correctly and the material flow results looked OK. Full set of generated files and results are here:

[generated-results.zip](https://github.com/NREL/celavi/files/8710409/generated-results.zip)

I dug into pylca_opt_foreground.py and discovered that when stage == 'cement co-processing', the output of line 285 is all NaN values because the flow names don't match. So one of the changes I made in the `array-uncertainty` branch or the `tiny-array-uncertainty` data branch must have caused this, but I'm not sure where to start debugging. I also know that the cement LCIA calculations are being treated differently because they're based on the input of material rather than final material demand, so that is likely related somehow.

Can you take a look and recommend a course of action? We can discuss further on Thursday too.

**Comment by TJTapajyoti** [comment]
![image](https://user-images.githubusercontent.com/24482959/169200235-8e2af99d-2714-4c30-a343-8da9be4db774.png)
 Trying to resolve this issue but getting this error.

**Comment by TJTapajyoti** [comment]
Solved! Please reclone data repo tiny uncertainty array
