### ISSUE TITLE
generated folder not being created automatically by code

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#162]
Generated folder if missing is not being created automatically

**Comment by rjhanes** [comment]
I'm unable to reproduce. I deleted the generated and results folders from my local data directory and tested code commit [93fcf87](https://github.com/NREL/celavi/commit/93fcf877db6458808f4aac506658947f0fa3a468) (`develop`) on data commit [e2de961](https://github.nrel.gov/akey/celavi-data/commit/e2de9615b091d1eab940eb017de758bcfcc6bd79) (`national_data`). Directories were created correctly and pre-processing files were saved to the generated folder.

@TJTapajyoti Can you confirm that you're using the code commit I referenced above?

@akey7 Can you try to reproduce as well?

**Comment by akey7** [comment]
@rjhanes I confirm that the generated and results folders are being created properly.
