### ISSUE TITLE
pyomo_postprocess method has unused parameters

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#164]
In insitu_emission.py, lines 116-118:

```
    def pyomo_postprocess(options=None, instance=None, results=None):
        df = pd.DataFrame.from_dict(model.s.extract_values(), orient='index', columns=[str(model.s)])
        return df
```

@TJTapajyoti Should the `model.s` variables inside `pyomo_postprocess` be `instance.s` instead, and do `options` and `results` also need to be used somewhere?

**Comment by TJTapajyoti** [comment]
This is obsolete now.
