### ISSUE TITLE
5_rtm_oaat_unc scenario file fails due to cost graph issue. 

### ISSUE THREAD

**Issue by TJTapajyoti** [NREL/celavi#169]
The error file is attached
[error.5_rtm_oaat.unc.txt](https://github.com/NREL/celavi/files/9245201/error.5_rtm_oaat.unc.txt)
d

**Comment by TJTapajyoti** [comment]
[5_rtm_oaat.txt](https://github.com/NREL/celavi/files/9245210/5_rtm_oaat.txt)

The yaml file is attached

**Comment by rjhanes** [comment]
The problem was a malformed YAML file. 5_rtm_oaat.yaml is updated in OneDrive; no coding changes were necessary to resolve.
