### ISSUE TITLE
Integrate visualization and plotting with results extraction from HPC 

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#19]
## Initial comment from @TJTapajyoti

1. Plot graphs using object file from CELAVI run. @akey 
2. Commit results successively to github results repo. 
3. Check to see if its possible from HPC directly. 

Issues - Graphs currently made with plotly are not working. Need to use seaborn. 

## Response from @akey7 

We still need to ensure that plotly cannot ave plots directly as png files. It might be able to and, if so, we should not use seaborn.

## Response 2 from @akey7 

I have confirmed that plotly will save plots with kaleido. We do not need to use seaborn.

**Comment by TJTapajyoti** [comment]
Issue resolved.
