### ISSUE TITLE
Runtime of CELAVI code - Increasing successively. IOWA runs failing

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#20]
## Initial comment

Runtime for CELAVI code is increasing successively.

IOWA run failed today because the first year 2001 is taking more than 15000 seconds in DES and Simpy.

Causes - Unknown.

Potential solutions? _ revert back to old code.
Check filtering properly?

Old code saved in scratch (Not deleted). Can compare from there.

## Followup comment

Comparing Aug 18 with Current code -

Changes in main.py

US WTDB was changed.

**Comment by TJTapajyoti** [comment]
Changes - 

New file for US DTWB
Transportation tracker.

**Comment by TJTapajyoti** [comment]
Hybrid repo did not work. Too many issues. Reverted everything back to old data and old repo and starting from fresh. Will develop step by step and let you know.

**Comment by TJTapajyoti** [comment]
Run 1 : IOWA Only with 18th Aug Data and code repo. 

**Status**

 29 minutes for complete run and creation of pickle file. 
Used routes_computed 191MB file which is the latest one. 
Used locations_computed old. 


 29 minutes for complete run and creation of pickle file. 
Used routes_computed 191MB file which is the latest one. 
Used locations_computed old.

**Comment by TJTapajyoti** [comment]
Run 3 : IOWA Only with 18th Aug Data and code repo.

Status

29 minutes for complete run and creation of pickle file.
Used routes_computed 191MB file which is the latest one.
Used number of turbines new

**Comment by TJTapajyoti** [comment]
Run 4 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
Used number of turbines new
Used location _computed new

Status
FAILED. Error in float and string manufacturing 93. Need @akey7 to help

**Comment by TJTapajyoti** [comment]
Run 4 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
Used number of turbines new
Used location _computed new
Corrected component.py manually with @akey7 help. 
Corrected __main__.py

Status
FAILED. unknown errors. 
Traceback (most recent call last):
  File "__main__.py", line 172, in <module>
    finegrind_material_loss=0.3,
  File "/home/tghosh/celavi/celavi/celavi/costgraph.py", line 154, in __init__
    self.build_supplychain_graph()
  File "/home/tghosh/celavi/celavi/celavi/costgraph.py", line 474, in build_supplychain_graph
    _fac_graph = self.build_facility_graph(facility_df = _line)
  File "/home/tghosh/celavi/celavi/celavi/costgraph.py", line 424, in build_facility_graph
    _facility_nodes = self.get_nodes(facility_df)
  File "/home/tghosh/celavi/celavi/celavi/costgraph.py", line 391, in get_nodes
    _attr_data)
  File "/home/tghosh/celavi/celavi/celavi/costgraph.py", line 249, in list_of_tuples
    raise NotImplementedError
NotImplementedError

**Comment by TJTapajyoti** [comment]
Run 5 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
ALL NEW input files **except** locations_computed.csv

Corrected component.py manually with @akey7 help.
Corrected main.py


STATUS:

**Comment by TJTapajyoti** [comment]
Run 5 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
ALL NEW input files
REinitialize cost graph

Corrected component.py manually with @akey7 help.
Corrected main.py

STATUS:

**Comment by TJTapajyoti** [comment]
Run 6 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
ALL NEW input files ( @rjhanes This is after the latest commit #892270e)
Reinitialize cost graph

Corrected component.py manually with @akey7 help.
Corrected main.py

STATUS:
FAILED. 


![image](https://user-images.githubusercontent.com/24482959/132797844-447581d2-f116-49cd-a01c-efe552a5f43a.png)

**Comment by TJTapajyoti** [comment]
Run 6 : IOWA Only with 18th Aug Data and code repo.
Used routes_computed 191MB file which is the latest one.
ALL NEW input files ( @rjhanes This is after the before the latest commit. Particularly I am working with #463d5f4)
Reinitialize cost graph

Corrected component.py manually with @akey7 help.
Corrected main.py

STATUS:
29 minutes for complete run and creation of pickle file.

**Comment by TJTapajyoti** [comment]
For further debugging and exploration, I will be using #463d5f4 from the data repo (Sep 8th 2021). Latest commit to repo seems to have an issue. @rjhanes

**Comment by TJTapajyoti** [comment]
Run 8 : IOWA Only with 18th Aug Data and latest code repo.
ALL NEW input files ( @rjhanes This is before the latest commit. Particularly I am working with #463d5f4 from data repo)
Using the netw.obj.. Saved cost graph file. 


STATUS:
 minutes for complete run.

**Comment by TJTapajyoti** [comment]
Run 9 : IOWA Only with 18th Aug and latest data code repo.
ALL NEW input files ( @rjhanes This is before the latest commit. Particularly I am working with #463d5f4 from data repo)
Using the netw.obj.. Saved cost graph file.

STATUS:
28 minutes for complete run.

**Comment by TJTapajyoti** [comment]
Run 10 : IOWA Only with 18th Aug and latest data code repo.
ALL NEW input files ( @rjhanes This is before the latest commit. Particularly I am working with #463d5f4 from data repo)
Using the netw.obj.. Saved cost graph file.
Using latest main.py and compute_locations.py. 

STATUS:
FAILED. Problem with data viz @akey7 

![image](https://user-images.githubusercontent.com/24482959/132806518-a099858b-216c-4bdf-97f2-3e082749a03c.png)

**Comment by rjhanes** [comment]
@TJTapajyoti I don't understand what information you need from me; can you clarify?

**Comment by TJTapajyoti** [comment]
Run 11 : updated main.py and compute_locations.py to latest files. Dataviz working fine. Issue - Installation of celavi module was not done on latest folder. 

STATUS:
Running in 29 minutes. Graphs created.

**Comment by TJTapajyoti** [comment]
> @TJTapajyoti I don't understand what information you need from me; can you clarify?

Hey @rjhanes So the issue is that after the latest commit to the data repo #892270e, I am getting errors while running. Before that, the code is running properly.

**Comment by rjhanes** [comment]
I'm going to create a new issue for that because it's separate from the model runtime debugging.

In the meantime, to continue with the model runtime debugging, use the most recent commit from the `national_data` branch that works. The commits from the last day or so only change (reduce in size) locations_computed and number_of_turbines so they won't affect runtime.

**Comment by TJTapajyoti** [comment]
> I'm going to create a new issue for that because it's separate from the model runtime debugging.
> 
> In the meantime, to continue with the model runtime debugging, use the most recent commit from the `national_data` branch that works. The commits from the last day or so only change (reduce in size) locations_computed and number_of_turbines so they won't affect runtime.

Thanks will do that. I know this is becoming a little confusing. I will send out an email soon outlining exactly what I am trying to get to..
