### ISSUE TITLE
Use config file to set input/output file locations and parameters in LCIA calculations

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#57]
The goal is to have the LCIA calculations set up similarly to the DES and CostGraph, with all file locations, directories, and parameters set through the Config file and processed in main.py. Currently a lot of the LCIA filenames etc. are hardcoded.

Specific tasks that I see (incomplete list):

- [x] Remove `os.chdir` call on line 159 of main.py - it will be unnecessary when the following tasks are completed
- [x] Replace hard-coded input filenames with filenames pulled from config (such as line 34 in pylca_celavi_background_postprocess.py)
- [x] Replace hard-coded output filenames with filenames pulled from config (such as line 150 in des_interface.py) - for the output files, also make sure the files are being saved to the outputs directory and not the pylca_celavi_data directory

To keep the config file in a consistent format, I recommend adding filenames to the `input_filenames` and `output_filenames` groups already in the config file. If there are additional parameters, another group called `lcia_parameters` or similar can be added to the file.

**Comment by TJTapajyoti** [comment]
Completed via PR #101
