### ISSUE TITLE
placeholder for any ideas for speeding up model runs

### ISSUE THREAD

**Issue by rjhanes** [NREL/celavi#7]
General ideas

- Reduce the number of calculations by identifying and avoiding duplicate operations
- Reduce problem complexity at the `Router` and/or `CostGraph` level - see #186 
- ~~Run the DES at the level of three components instead of individual components - that is, at the level of one turbine of blades instead of one blade~~ see issue #63 for progress on this item
- Make pathway selections by `facility_id` and store, to avoid finding shortest pathways for every blade which requires many calls to `CostGraph` methods.
- Run `CostGraph` and `pylca` every 2 or 5 years instead of annually. `CostGraph` has a config parameter that controls the run frequency; `pylca` needs this functionality added.

**Comment by TJTapajyoti** [comment]
LCA calculation time reduced drastically with pyLCA V2.0

**Comment by rjhanes** [comment]
Closed - the model is pretty well as fast as it can be without refactoring for parallelization
