### ISSUE TITLE
Incorporate state-level electricity mix in LCA calculations

### ISSUE THREAD

**Issue by eberlea** [NREL/celavi#83]
- Change from national to state-level mix 
- Potential data source for current state-level electricity mix: https://www.epa.gov/egrid/data-explorer (2019 data: [Resource Mix by all fuel types, by state, 2019.csv](https://github.com/NREL/celavi/files/7437652/Resource.Mix.by.all.fuel.types.by.state.2019.csv))
- Could modify future mix based on ReEDS scenario

**Comment by TJTapajyoti** [comment]
Obtained state level electricity mix projections from 2020 to 2050. 

Things to do once PR #101 is merged with develop.

2000 to 2010 - Electricity is replaced with generic 2010 electricity mix for USLCI.
DES model to send states along with material flow information
Send state information to pylca_opt_foreground
Change preprocessing function to include state.
Drop state after selection and use LCI for particular state 
return the results with the state information.

**Comment by TJTapajyoti** [comment]
to - do  DES to send state information @akey7
