### ISSUE TITLE
Expose melted dataframes from diagnostic viz to write as csvs

### ISSUE THREAD

**Issue by akey7** [NREL/celavi#92]
- [x] Return melted dataframes from the plotting method
- [x] Write csvs from melted dataframes at end of each, rather than the wide dataframes. 
- [x] Correct extra space in logging statement `2021-11-03 11:06:28.257875 In While loop pylca interface`
- [x] Get rid of hard-coded `blade_mass.csv` filename in `__main__.py`

**Comment by rjhanes** [comment]
Closed with PR #98
